linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - gofmt
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: empty-block
        disabled: true
      - name: redefines-builtin-id
        disabled: true

run:
  deadline: 5m
  tests: true
  build-tags:
    - all

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
