linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - gofmt
    - misspell

run:
  deadline: 5m
  tests: true
  build-tags:
    - all

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
